### ISSUE TITLE
can write an example of koa-restql?

### ISSUE THREAD

**Issue by jjz** [Meituan-Dianping/koa-restql#6]

**Comment by crzidea** [comment]
Thank you for your advice. I would like to add an example later.

At the time, you can follow the README and [tests](https://github.com/Meituan-Dianping/koa-restql/blob/master/test/restql.js) for a good start.

**Comment by crzidea** [comment]
After all, I will appreciate if you can help us add an example.

**Comment by crzidea** [comment]
Thanks!

**Comment by crzidea** [comment]
We have added a very simple example [here](https://github.com/Meituan-Dianping/koa-restql/blob/master/examples/server.js) to help beginners starting their project.

You can add some more examples, or let us know if you got problems with starting an example.

**Comment by jjz** [comment]
@crzidea I worte an example according to your TEST，In the form of package use koa-restql，I don't need to write any API releated content。example:[https://github.com/jjz/koa-restql-example](https://github.com/jjz/koa-restql-example)

**Comment by crzidea** [comment]
Nice work!
