### ISSUE TITLE
when I run the examples\server.js,throw a exception

### ISSUE THREAD

**Issue by markflyfly** [Meituan-Dianping/koa-restql#8]
`C:\Users\mark\Desktop\koa-restql-master\test\lib\prepare.js:55
      let {
          ^

SyntaxError: Unexpected token {
    `
![image](https://cloud.githubusercontent.com/assets/15846359/18744709/b08e90d0-80f1-11e6-9f8c-b66bf4a4bd6e.png)

**Comment by crzidea** [comment]
It sounds like problem of node version. We only support node v6 at the time.
Besides, We only tested the package on Unix (no test on Windows).

**Comment by crzidea** [comment]
You can try `Windows Subsystem for Linux (beta)` if you develop on Windows 10.

**Comment by markflyfly** [comment]
thanks, it's the problem of node version,my node version is v5.0,and then I update to the v6,and start the server,it's ok!

**Comment by markflyfly** [comment]
I think you can add the runtime environment needed，that's better

**Comment by crzidea** [comment]
#9

I have edited README.

**Comment by markflyfly** [comment]
Yesterday, I actually have used babel turn your code, it prompts this error
![image](https://cloud.githubusercontent.com/assets/15846359/18778787/a38bf9f6-81a8-11e6-8d2c-7b2aee6c6e0d.png)
is the windows system problem?

**Comment by crzidea** [comment]
That IS Windows problem...
The best way to avoid this kind of problems is to use `Windows Subsystem for Linux` since we do not have any plan to solve this kind of problems.
